name: ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
    run-eslint:
    name: Run ESLint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check ESLint Error
      	env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.SECRET_KEY }}
        uses: reviewdog/action-eslint@v1
        with:
          github_token: ${{ secrets.SECRET_KEY }}
          reporter: github-pr-check
          fail_on_error: true
      - name: Check ESLint Review
      	env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.SECRET_KEY }}
        uses: reviewdog/action-eslint@v1
        with:
          github_token: ${{ secrets.SECRET_KEY }}
          reporter: github-pr-review
          fail_on_error: true
          
